### ISSUE TITLE
Resultado do valor do CEP texto para o SEDEX e PAC

### ISSUE THREAD

**Issue by radamiBR** [pedro-teixeira/correios#365]
Olá como eu faço nos resultado dos valores do correios em Sedex e PAC abaixo do valor colocar textos diferente para cada.

Estou usando PAC como frete grátis tem como não exibir valor R$ 0,00

Tentei chamar por s_method_pedroteixeira_correios_04162 não deu certo.

Como posso fazer, obrigado

**Comment by rafaelpatro** [comment]
Boa tarde @radamiBR 

Para adicionar um texto abaixo da cotação, pode fazer via CSS. Segue exemplo:
```css
label[for=s_method_pedroteixeira_correios_04162]::after {
    content: "Sujeito a atraso devido a greve";
    display: block;
    color: #999;
}
```
![image](https://user-images.githubusercontent.com/13813964/40879019-2067fa3a-6670-11e8-804b-2cf29ce58316.png)

**Comment by radamiBR** [comment]
Valeu rafael, tem como deixar R$ 0,00 com hide para não exibir o valor no simulado e onepage.

**Comment by radamiBR** [comment]
Valeu rafael, tem como deixar R$ 0,00 com hide para não exibir o valor no simulado e onepage.

**Comment by rafaelpatro** [comment]
Para ocultar o valor no Flat Rate pode fazer como ilustrado abaixo.
```css
label[for=s_method_flatrate_flatrate] .price {
    display: none;
}
```

Infelizmente não é possível identificar o valor 0,00 pelo CSS. Se quiser ocultar valores nulos para o Correios, precisará alterar seu template [neste trecho](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/design/frontend/rwd/default/template/checkout/cart/shipping.phtml#L105):

![image](https://user-images.githubusercontent.com/13813964/40880117-8634a3b6-6681-11e8-8a8b-17a352abf0ed.png)

Substituir a linha em destaque pelo trecho a seguir:
```php
<?php if ($_rate->getPrice() > 0) : ?>
    -
    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
<?php endif; ?>
```
